[meta]
name        = "Topbar"
author      = "fd268"
category    = "Race"
version     = "1.0.0"
[script]
dependencies = [ "NadeoServices" ]
optional_dependencies = [ "ChampionMedals","WarriorMedals" ]